# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='torrentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torrentName', models.CharField(max_length=300)),
                ('torrentLink', models.CharField(max_length=500)),
            ],
        ),
    ]
