# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrentzone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentmodel',
            name='torrentInfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
